### ISSUE TITLE
No vertical scroll on detail

### ISSUE THREAD

**Issue by DevineJasper** [Aqro/gooey-hover-codrops#1]
What an amazing project! It's beautiful and so delightful.

However,  when I click on an image and go to the detail view, I am not able to scroll vertically.

I've put a height: 100% on the _aside class="detail-view"_ which makes the scrollbar visible when you're on a detail page, however, scrolling does not work. You can navigate down with the scrollbar though.

When you scroll on a detail page,  the _H1 element_ & the _div class="scroll-content"_ both change their x-value in the transform: translate3D CSS styling.

Any idea how the vertical scrolling with a mousewheel can enable on a detail-view?

**Comment by Aqro** [comment]
Hi Jasper 👋
Actually, it wasn't supposed to be a 100% working website, just a demo.

To enable scroll on a detail view, you probably should init multiple scrollbars and switch between them depending on the view. You can check on [Smooth scrollbar repo](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md) for more details.
